### ISSUE TITLE
[ED] Repetitive words

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#10]
Web and Access(ibility) are exhaustively used. Maybe we could cut them down to make it more readable.

**Comment by shawna-slh** [comment]
Well the page is an introduction to web accessibility! :-)

I did a quick pass and didn't see any to change[1]. Please let us know if you have specific suggestions. I'll also keep it in mind with next thorough edit pass.

[1] With one exception: I previously went back and forth on the heading

> Examples of Web Accessibility

or just 

> Examples

I'll try the later this time and see if anyone dislikes it...
