### ISSUE TITLE
[!!] Typos/Grammar/Simplification

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#11]
There are a few typos and grammar issues that I was able to find. I’m happy to provide a pull request once we know what alternative we go with. Listing some for illustration and as a reminder.

* First sentence is passive voice: “Properly designed and coded websites and tools can be used by people with disabilities.” => “People with disabilities can use properly designed and coded websites.”

* > However, currently many sites and tools are developed with accessibility barriers that make it difficult or impossible for some people to use them. 

  =>

  > But currently, many sites and tools are developed with accessibility barriers that make it difficult or impossible for some people to use them.

* “high quality” => “high-quality”

* “Web accessibility means that people with disabilities can use the Web. More specifically, it means people with disabilities can:” => Quite repetitive. “Web accessibility means people with disabilities can use the web. They can:”

* “in order to” => ”to“

* “We encourage you to explore this website, or look through the WAI Resources list.” => “We encourage you to explore this website or look through the WAI Resources list.”

* “people using a slow Internet connection, or how have limited or expensive bandwidth” => “people using a slow Internet connection or have limited or expensive bandwidth”

**Comment by bakkenb** [comment]
[ED]  "Some accessibility solutions take more time and effort."  -->  "Some accessibility solutions take more time and effort to implement."

**Comment by shawna-slh** [comment]
Thanks.

I fixed the ones above that I agree with. Happy to discuss the others.

**Comment by yatil** [comment]
Link to the commit?

**Comment by shawna-slh** [comment]
I did them in a couple of different commits - along with other things. They're implemented in latest:

https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/

**Comment by yatil** [comment]
Then I have nothing to discuss for now.
