### ISSUE TITLE
[ED] Video Thumbnail/Embed

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#13]
Many use videos to get a gist of a subject matter. It might be a good idea to have the 4-minute video either embedded or as a graphical link. I think the video should be more discoverable.

**Comment by shawna-slh** [comment]
done.

**Comment by yatil** [comment]
[FTR: The decision is to embed the thumbnail which we have no design for right now. Made a note to create/implement design for thumbnails: w3c/wai-website-design#107.]
