### ISSUE TITLE
[!!] update after business case revised

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#15]

**Comment by yatil** [comment]
Related to this: This link links to just the business case:

[Web Accessibility Benefits People With and Without Disabilities](https://www.w3.org/WAI/bcase/soc#groups)

Either link to the archived version: https://www.w3.org/WAI/business-case/archive/soc or update link to reflect the new business case.

**Comment by shawna-slh** [comment]
This wording is based on specific points in the [old business case](https://www.w3.org/WAI/business-case/archive/Overview):
> There is also a strong business case for accessibility. Accessibility overlaps with other best practices such as mobile web design, device independence, multi-modal interaction, usability, design for older users, and search engine optimization (SEO). Accessible websites can have better search results, reduced maintenance costs, increased audience reach, and demonstrate corporate social responsibility (CSR).

We could cut it down to just the 4 main topics in the [new business case](https://www.w3.org/WAI/business-case/):
> There is also a strong business case for accessibility. Accessibility can drive innovation, enhance your brand, extend market reach, and minimize legal risk.

Or, do we want to do something in between? (one idea for reworking this list is in https://github.com/w3c/wai-intro-accessibility/issues/37

**Comment by sharronrush** [comment]
Suggestion:
There is also a strong business case for accessibility. Studies show that accessible design improves overall user experience and satisfaction, especially for older users and across different browsing devices. Accessibility has been proven to drive innovation, enhance your brand, extend market reach, and minimize legal risk.

**Comment by shawna-slh** [comment]
I realized that some of that is already in the previous section and in the next sentence. :-)
