### ISSUE TITLE
Small nit-picky thing...

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-intro-accessibility#18]
Is it possible to move the link "video Intro to Web accessibility..." either above or below the thumbnail? 

Further down the page it is above so that seem like the best option for consistency.

**Comment by a11ycob** [comment]
Another question, possibly for Eric, on the semantics of the `<aside>`s. Are we sticking with `<header>` tags within these contentinfo areas, or is it easier/better to have it follow logical heading structure, so in most cases an`<h3>` instead of a `<header>` tag? To be honest, I'm not overly familiar with the `<header>` use case, so it may be my ignorance here.

**Comment by shawna-slh** [comment]
/me moved second point to separate GitHub issue https://github.com/w3c/wai-website-design/issues/113

**Comment by shawna-slh** [comment]
Anything is possible. :-)

And I agree with this suggestion.

Done.
