### ISSUE TITLE
[ED] Linking to local page once and to youtube on another place

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#24]
The first video links to a page on w3.org/WAI, the second one directly to youtube. I think we should choose one way to do it. (I am aware that we currently don’t have a page for this particular perspectives video.)

**Comment by shawna-slh** [comment]
Maybe would be good to have a WAI page for the compilation (with AD version and captions).

Think not a high priority for now.

Added "_(YouTube)_" to link that goes off site.
