### ISSUE TITLE
[ED] heading/sectional cues

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-intro-accessibility#25]
I thought all the edits were helpful. Some of the bolding that was removed I think leads to some sections having long sections of text without "heading/sectional cues," particularly in the "Accessibility is Important for Individuals, Businesses, Society." But this is definitely an ED issue. Nice work.

**Comment by shawna-slh** [comment]
Thanks for input Howard. (Personally I liked the some of the bolding, but went with others' preference against it.)

I agree that section is long. I had noted it, but not tackled it further.

After working through it some more, I don't think it makes sense to add headings. I did:
* Delete "An accessible Web can also help people with disabilities more actively participate in society." _(While it is a good point, I think it's not worth the text given good coverage of the broad issue in the rest of that section.)_
* bullet end of: "Accessibility supports social inclusion for people with disabilities as well as others, such as older people, people in rural areas, and people in developing countries."

Updated in [Accessibility is Important for Individuals, Businesses, Society](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#important)
