### ISSUE TITLE
[ED] required by law in some [cases|countries]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#26]
@AndrewArch from [survey](https://www.w3.org/2002/09/wbs/35532/Intro-Review-2018-Jan/results):

> 2. consider "Web accessibility is required by law in some countries" (rather than "... in some cases")

**Comment by shawna-slh** [comment]
/me now realizes that having "cases" might be confusing with "law".

While I agree that reads better, in reality, it's not that clear cut.
For example, in some countries it's required by law only for some types of websites.

Could do:
> Web accessibility is required by law in some situations.

or: 
> Web accessibility is required by law for some websites, applications, and tools.

---

I also wonder if we can say "many" instead of "some"?

> Web accessibility is required by law in many situations.

or: 
> Web accessibility is required by law for many websites, applications, and tools.

**Comment by AndrewArch** [comment]
@slhenry re 'some types of websites' - also only for some sectors (eg public sector or education sector)

I do like 'many' instead of 'some' - adds more emphasis :)

**Comment by shawna-slh** [comment]
> re 'some types of websites' - also only for some sectors (eg public sector or education sector)

Yup, that's more accurate.

> I do like 'many' instead of 'some' - adds more emphasis :)

Agree. Just want to make sure that we are comfortable that "many" is true. (I think so.)

**Comment by yatil** [comment]
This is an introduction document. We don’t need to be accurate here but give a good overview. For example, sometimes the country has no law, but the state has. Or there are local policies. It quickly gets difficult to include every circumstance. 

I do not feel to include tools… Is there a law on the accessibility of screwdrivers? :-D A tool, as I understand it, is just some type of application.

What about something along the lines of:

> Laws and policies regulate accessibility for websites and applications in many countries. See [laws and policies](…) for more information about your local regulations.

That said, this is totally editor’s discretion.

**Comment by vavroom** [comment]
I tend to agree with @yatil about the introductory aspect of the text. I also like the more active way his suggestion reads. However, reading the sentence *seems* quite heavy, though I can't figure out how to simplify it without significantly removing meaning.

**Comment by sharronrush** [comment]
+1 to @yatil's version. Is it less heavy by putting the countries first? ie, 
"Many governments regulate website and application accessibility. See [laws and policies](https://www.w3.org/WAI/Policy/) for more information about your local regulations."

**Comment by yatil** [comment]
+1 to @sharronrush’s version, that reads very straight-forward to me.

**Comment by shawna-slh** [comment]
I think there is some misunderstanding. I don't think Andrew and I were suggesting that we add wording to the document about sectors, etc. we were just discussing the background for choice of wording.

Important: Please see that one sentence in context &mdash; it is the last paragraph before More Info under In [Accessibility is Important...](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#important). 
I'm not keen on expanding or complicating the information in that one simple, direct paragraph.

I think the basic message is important to keep: **Web accessibility is required by law**
**_The only question was what qualifier needed to be added to that._**
(Who complicated this issue??? ;-)

**Comment by shawna-slh** [comment]
This is a nicer way of saying: Your website, web application, and web tool might be required to be accessible by law.

That's how I hope people read it.

/me starts to think of more active voice options, but I think this is OK not.

**Comment by shawna-slh** [comment]
As agreed in [1 Feb telecon](https://www.w3.org/2018/02/01-eo-minutes.html#item04), changed to:

> Web accessibility is required by law in many situations.
