### ISSUE TITLE
[ED] no Intro or Context heading

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#28]
@nitedog  from [survey](https://www.w3.org/2002/09/wbs/35532/Intro-Review-2018-Jan/results):

Is the "Introduction" section really necessary? It seems to merely repeat what is in the immediately following section "Accessibility in Context". Also, if the "Introduction" section is removed, do we need the *heading* "Accessibility in Context"? Might be nice to dive right into the content - seems more engaging.

**Comment by shawna-slh** [comment]
### Background

One of the recommendations we gleaned from usability testing was to have a summary at the top of most pages. That's something we're leaving as "to try" but not required for all pages. The 2 sentences under "Introduction" started out under Summary, but they aren't really a summary of the whole page content. Sharron had an idea to change Summary to Introduction, and it was done.

Summary up front I think is less important for this resource. For some resources, it's good to let people know what the page is about. "Introduction to Web Accessibility" is pretty clear, though. :-)

Also, while some of our resources we think many people will just skim, with this one, I think the primary target audience (who is wanting to understand accessibility), will read it more carefully.

### Fresh Thinking

Originally, I was thinking it would be good to **get that point clear and succinct up front**.

However, re-reading it all, I agree that what's under Introduction is basically a summary of what immediately follows, and maybe a tad awkward if you read the next part carefully.

... although one thing that's not as clear in the next section is "currently many sites and tools are developed with accessibility barriers."

I do still wonder if we want that up front?

### Options

Here are some approach to consider:

[1. Introduction as is](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/)
_(Consider edits if leave it?)_

[2. No Introduction and no "Accessibility in Context" heading](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/alt-intro-no)
_(I think it looks a bit awkward without the heading. Also, for people who use headings, they might miss that first content some?)_

[3. No Introduction and **with** "Accessibility in Context" heading](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/alt-intro-context)

### EOWG Input Requested

At this point I don't feel super strongly for or against either option.

EOWG folks: Please add your input _from the point of view of different readers[1]_ with rationale (not just "I like option X") &mdash; keeping in mind people's misunderstandings, preconceived notions, myths, etc.

_[1]  I find particuarly helpful [this reader-train-of-thought](https://github.com/w3c/wai-intro-accessibility/issues/5#issuecomment-358126950) "When I look at Alt 5, my minds says,...". I tried to do somtehign like that at the top of [27](https://github.com/w3c/wai-intro-accessibility/issues/27#issuecomment-362114439) with "If we sent them to the landing page, they'd have to process the information on that page, and figure out to click on one, then go to a new page, then start the video... then..."_

**Comment by a11ycob** [comment]
The TBL quote is important as it encapsulates the original intent of the web. I believe it provides a focus of sorts. We all need that reminder occasionally. 

That being said, I also think that in order to jump right into the heart of content, the "What is Accessibility" section needs prominence, and should be elevated. We could move the "Accessibility in Context" section down the page or made as an aside.

**Comment by yatil** [comment]
I feel the introduction is redundant. On mobile, it is several screens of text until I get to the core of the question, “what is accessibility”. I would probably:

* Remove the introduction
* Put the Tim Berners-Lee quote directly underneath the “page contents box”
* Then the “What is Accessibility” section
* Video Introduction link
* “Accessibility in Context” section

That said, it is Editor’s discretion, so I’m fine with what Shawn decides (after group input).

**Comment by sharronrush** [comment]
+1 to Chris and Eric's suggestion to move What is Accessibility as the first section. Could even include what is currently the Introduction section as a lead in to that content. Also think Eric is on the right track with his ordering but, yes ED.

**Comment by shawna-slh** [comment]
Reminder that the organization of the content was approved in this survey: https://www.w3.org/2002/09/wbs/35532/Intro-Review-2018-Jan/results

There was just this one Editor's Discretion comment about removing one section and heading. I did ask for input on that one point. Do we really want to open up a new issue on significantly re-arranging the content at this time – after EOWG has approved it and we're wrapping up for publication?

Since it came up, notes on rationale for current organization:
* Put the compelling, powerful content first.
* Many people have fundamental misunderstandings about web accessibility, including that it is *_**something extra that you have to add**_* to make websites accessible. I think the most important outcome of this page is combating these perspectives, and changing the way people feel about web accessibility. The "Accessibility in Context" section is intended to do that.
* I think most people have a general idea of what web accessibility is. Even if they've never heard of it, they have a good guess based on their knowledge of "accessibility" in general. (This was apparent in usability testing in Oct [caveat: small # of people].)
* The "What is Web Accessibility" section doesn't provide significantly new or enlightening info for most people. Some people read or skim the first few paragraphs of most pages, then stop. If this was the first section, some won't read past it, and they'd miss the very important messages in "Accessibility in Context" 
* "What is Web Accessibility" is linked at the top in the Page Contents, so readers and skimmers 1. Know that section is there, and 2. Can jump directly there if they want. It is the first, second, or third link in the options above.

**Comment by shawna-slh** [comment]
I had another idea last night. I'm not sure if I like it or not.

> ... although one thing that's not as clear in the next section is "currently many sites and tools are developed with accessibility barriers."
I do still wonder if we want that up front?

An idea is to add that point to the [Accessibility in Context section](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#context)

Below is that text for context, with the last sentence added: "Currently many websites are difficult or impossible for some people with disabilities to use."

> The Web is fundamentally designed to work for all people, whatever their hardware, software, language, location, or ability. When the Web meets this goal, it is accessible to people with a diverse range of hearing, movement, sight, and cognitive ability.

> Thus the impact of disability is radically changed on the Web because the Web removes barriers to communication and interaction that many people face in the physical world. However, when websites, applications, technologies, or tools are badly designed, they can create barriers that exclude people from using the Web. Currently many websites are difficult or impossible for some people with disabilities to use.

(I realize that makes that paragraph long, and if folks like that sentence there generally, I will draft breaking up the paragraphs differently and see if I have a different suggestion.)

[Please note that other than that last sentence, the rest of this text has been approved by EOWG. Please carefully consider before raising new comments on the rest of the text.]

**Comment by shawna-slh** [comment]
Notes from [1 Feb EOWG telecon](https://www.w3.org/2018/02/01-eo-minutes.html#item04):

* Sarah says " I actually like the intro. Its succinct and quotable"
* Amanda: Not strong feelings perfectly happy with the various comments, but have resonance with Eric's comments about mobile and how long it would take to get to that info.
* Shawn: Does it matter that the TOC is there at the top make a difference? [so people can click on it directly if they want]
* Matt: There should be a heading there before text begins, that is the only thing I disagree with.

**Comment by shawna-slh** [comment]
+1 to Sarah. I do like that aspect of it.
/me poking around, sees that [Norah likes it](https://github.com/w3c/wai-intro-accessibility/issues/3#issuecomment-358448196), too.

I'm working on if there's a way that we can present it better -- with different heading and possibly different visual.

/me brainstorms headings and puts here in case someone else wants to help...
* sound bite
* the bottom line
* background
* the basics
* in a nut shell
* the premise
* summary (but just those 2 sentences are not a summary of the whole page, see https://github.com/w3c/wai-intro-accessibility/issues/6)
* If you only read 2 sentences, read these :-)

**Comment by shawna-slh** [comment]
Trying revised Summary option. Closing this and re-opening https://github.com/w3c/wai-intro-accessibility/issues/6
