### ISSUE TITLE
[!!] simple statement (like definition, but not) of web accessibility

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#3]
Currently we say:
> Web accessibility means that people with disabilities can use the Web. More specifically,...

I have some concern that this could be misunderstood that it's the responsibility of people with disabilities -- not the websites and web technologies to be accessible. Some might think it means:
* People with disabilities have the tools that they need to use the Web (there *are* some people who don't understand that websites have to do things for accessibility, and think that just if people have the right assistive technologies, then the Web will automatically work for them)
* People with disabilities have the skills they need to use the Web

I considered something like this to address that:
> Web accessibility means that websites, tools, and technologies are designed so that people with disabilities can use the Web. More specifically,...

(or more simply:
> Web accessibility means that websites, tools, and technologies are designed so that people with disabilities can use them. More specifically,...

Pros:
* makes more clear that it is the responsibility of websites, tools, and technologies

Questions:
* would "designed" in that context be misunderstood as like visual designers, rather than the broad idea of design? would "designed and developed" be better? or not worth the added words?
* does it need "websites, tools, and technologies" or can that be shortened?

What are your thoughts -- on:
* whether we need to be concerned with potential misunderstanding _or not_
* the idea above
* other ideas
???

**Comment by a11ycob** [comment]
I think your approach is sound, Shawn. Asking questions like this will allow us to get an accurate and concise definition.

Here is a slightly different kick at the can:

Web accessibility facilitates the creation of websites, tools, and technologies that can be used by the widest audience possible, in a manner of their choosing.

**Comment by shawna-slh** [comment]
Note the we want to keep focus of "accessibility" on **disabilities**. For background, see [Accessibility, Usability, and Inclusion](https://github.com/w3c/wai-inclusion/blob/gh-pages/index.md)

**Comment by Sylduch-Conseil** [comment]
I prefer @slh's approach as the sentence suggested by @a11ycob. 
In my opinion, accessibility does not people create web content, or digital content, even if accessibilith is not used, web content can be created. But if a site or content is not accessible, it will prevent people with disabilities from accessing this content, from getting the content information. 
So it is important to mention people with disabilities in this sentence. 
I am ok with Shawn's first or second proposal.

**Comment by jespulido** [comment]
How about this. I don't think I've seen this suggested anywhere, but I tend to prefer the words like "enable" and "empower." So what if it said something like
"Web accessibility enables people with disabilities to use Web sites and Web applications effectively."
or "Web accessibility enables people with disabilities to use the full functionality of Web sites and Web applications."

**Comment by bakkenb** [comment]
Of @slhenry's examples, I prefer the second as it is more straight forward. However I remember some discussion about possibly not using the word "means" because it sounds like a definition again. 

Another thing I like about that statement is the addition of the words "tools, and technologies" so that the statement is about more than just web content.

Another suggestion...
> Web accessibility enables people with disabilities to more effectively use websites, tools, and technologies. More specifically,...

**Comment by iamjolly** [comment]
I'm like both:

> Web accessibility means that websites, tools, and technologies are designed so that people with disabilities can use them. More specifically,... (@slhenry)
and
> Web accessibility enables people with disabilities to more effectively use websites, tools, and technologies. More specifically,... (@bakkenb and @jespulido)

I'm OK to let this go to editor's discretion.

**Comment by a11ycob** [comment]
While I agree with the specificity of referring to PwD is important, accessibility, generally speaking, provides better solutions for all, We often talk about the "unintended benefits of accessibility", as well as those who find themselves in temporary or situational contexts that allow them to benefit from accessibility also.

I guess what I am concerned with is being so specific that we lose some of the depth of the movement as a whole.

**Comment by vavroom** [comment]
I like the second of the two options offered by @slhenry 

If 'design' is a concern, we might want to entertain the idea of 'create'.

While I'm ok with the idea of 'enable', I have strong objections to the use of the word 'empower' in this context. You may provide the tools, or the environment where someone will empower themselves. But you cannot empower them. The very notion of empowering someone else seems to me to be disempowering. To give power to someone else, you have to be in a position of power to begin with. Empowerment isn’t about power given, but about power taken.

**Comment by nrhsinclair** [comment]
I really like your introductory paragraph at the top of the page: 

> Summary
Properly designed and coded websites and tools can be used by people with disabilities. However, currently many sites and tools are developed with accessibility barriers that make it difficult or impossible for some people to use them. This page explains more about...

That introduction provides an excellent context for everything that comes after it including the web accessibility statement. I prefer the second statement and think it is less likely to be misunderstood: Web accessibility means that websites, tools, and technologies are designed so that people with disabilities can use the Web. More specifically,... 

I think "designed and developed" is a stronger statement and should be used.

**Comment by hkramer** [comment]
I like Shawn's first version: Web accessibility means that websites, tools, and technologies are designed so that people with disabilities can use the Web.

**Comment by shawna-slh** [comment]
@a11ycob I think it is good to include those additional benefits throughout this introduction. I also think it is important to keep the simple statement focused on people with disabilities. 

This was part of the motivation behind:  [Accessibility, Usability, and Inclusion](https://github.com/w3c/wai-inclusion/blob/gh-pages/index.md)  (I wonder if that's not clear there? :-/)

**Comment by shawna-slh** [comment]
Re: "Web accessibility enables people with disabilities to more effectively use websites, tools, and technologies. More specifically,..."

I'm a little hesitant to include "more effectively" because it could be misunderstood that without accessibility, people with disabilities can use them, just not as effectively. In reality, without accessibility, some people with disabilities can't use them at all.

**Comment by shawna-slh** [comment]
Thanks for all the insight! Based on all above:

This is shorter and smoother:

> Web accessibility enables people with disabilities to use websites, tools, and technologies. More specifically,... 

However, I think it still does not clearly enough put the responsibility on the design and development. Also seems more like it's a special thing that you have to do to enable people.

I'm leaning towards this:

> Web accessibility means that websites, tools, and technologies are designed and developed so that people with disabilities can use them. More specifically,...

**Comment by yatil** [comment]
[**Preliminary resolution**: Group OK with the second option in the [meeting on January 18](https://www.w3.org/2018/01/18-eo-minutes.html).]

**Comment by shawna-slh** [comment]
Resolution from [18 Jan teleconference](https://www.w3.org/2018/01/18-eo-minutes.html#item04):

> Web accessibility means that websites, tools, and technologies are designed and developed so that people with disabilities can use them. More specifically,...

Resolution will be listed in EOWG survey for all to review. Can also re-open this issue if concerns...

**Comment by brewerj** [comment]
Glad to see "...and developed" added following "designed." I don't think that it works without that.

**Comment by yatil** [comment]
/me does not want to go into semantic details here, but “designed” did never refer to “how it looked” but how everything works together. The development is a result of a good design. I think on a WAI website it is always a good idea to call out development, too. :-)
