### ISSUE TITLE
Editorial feedback: Length of resource

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#34]
@HerinHentry asked in https://github.com/w3c/wai-website/issues/26:

> This page is a great collection of information. It feels a bit long though. Is it possible to split this into individual sections? Looking at a mobile screen, it scrolls forever.

**Comment by shawna-slh** [comment]
I think conceptually it's important for it all to be on one page.

One thing we could do is make the "More Info on..." boxes collapsed by default. However, I'm not yet convinced that's worth the added complexity.

**Comment by yatil** [comment]
I think I generally agree with @slhenry, the page also changed a little bit since the issue was raised in March 2018, which helped the skimability.

**Comment by sharronrush** [comment]
I agree with Shawn, conceptually it is one topic. The individual sections are immediately available through the TOC, which addresses the scrolling issue. I think it is fine as is.

**Comment by bakkenb** [comment]
I can see how many of our pages could/would be lengthy on a mobile device. I think that is the nature of content that is used to teach and explain things. I would not like to see this content broken up into separate pages because it is all very cohesive and flows well.
