### ISSUE TITLE
What is “multi-modal interaction”?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#37]
This came up working with the translator to German. The following paragraph speaks of “multi-modal interaction”.

> **There is also a strong business case for accessibility.** Accessibility overlaps with other best practices such as mobile web design, device independence, multi-modal interaction, usability, design for older users, and search engine optimization (SEO). Accessible websites can have better search results, reduced maintenance costs, increased audience reach, and demonstrate corporate social responsibility (CSR).

This phrase is very jargony and even if you know what it is, hard to explain. Especially for the audience of this document it might be good to not use it. Maybe we could just say: 

> **There is also a strong business case for accessibility.** Accessibility overlaps with other best practices such as:
> 
> * designing for the mobile web,
> * different devices,
> * different input modes like speech, touch, and mouse,
> * different output modes like screen readers, browsers, or ebook displays,
> * usability,
> * designing for older users, and 
> * search engine optimization (SEO). 
> 
> Accessible websites can have better search results, reduced maintenance costs, increased audience reach, and demonstrate corporate social responsibility (CSR).

(The first part of the last sentence also is the last point on the list, so we might want to simplify there, too.)

**Comment by shawna-slh** [comment]
will be addressed in https://github.com/w3c/wai-intro-accessibility/issues/15#issuecomment-496744750
