### ISSUE TITLE
Inelegant phrasing

### ISSUE THREAD

**Issue by yatil** [w3c/wai-intro-accessibility#38]
This issue was raised working with the German translation:

> Most of the basics of accessibility are fairly easy to implement. If you are new to accessibility, it takes some time and effort to learn the common issues and solutions.
> 
> Some accessibility barriers are more complicated to avoid. Some accessibility solutions take more time and effort to implement.
> 
> It is most efficient and effective to incorporate accessibility from the very beginning of projects and throughout organizations.

The two first paragraphs are worded in a way that makes them hard to understand. It goes from implementing to avoiding back to implementing and then back to avoiding by incorporating it from the very beginning.

What about this rewrite or something similar:

> The basic principles of accessibility are fairly easy to learn but it takes some time to familiarize yourself with all the common issues and their solutions. It is most effective and efficient to incorporate accessibility from the very beginning of projects to avoid barriers that are more complicated to avoid.

**Comment by shawna-slh** [comment]
**See it in context: [Making Your Website Accessible](https://www.w3.org/WAI/fundamentals/accessibility-intro/#website)** (This is the entire text of that section.)

For EOWG input, here's a pass at saying what we want to get across in language that is more simple and direct. 

> Most of the basics of accessibility are fairly easy to implement. If you are new to accessibility, it takes some time to learn the basics.

> Some accessibility solutions are more complex and take more effort to implement.

> It is most efficient and effective to incorporate accessibility from the very beginning of projects and throughout organizations.

**Comment by shawna-slh** [comment]
https://github.com/w3c/wai-intro-accessibility/pull/41/files
