### ISSUE TITLE
[ar] Intro page title in secondary nav is in EN instead of AR

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#49]
in EN incorrectly: https://www.w3.org/WAI/fundamentals/accessibility-intro/ar
in AR correctly: https://www.w3.org/WAI/videos/standards-and-benefits/ar

@yatil - *not* at all tea, low-ish priority

**Comment by yatil** [comment]
I added the translation to the translation file in https://github.com/w3c/wai-website-data/commit/d3be5e2d698969739bdc368f190b47f294555c88 – It will be updated when we update the website next time.
