### ISSUE TITLE
[ko] ready for Korean translation

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-intro-accessibility#67]
@yonguilee Do you want to do this translation? :-)

**Comment by yonguilee** [comment]
@shawna-slh 

I'll do~

**Comment by shawna-slh** [comment]
Yeah! I'm excited. Then we will have all of the main navigation pages in Korean! I will use [your translation for the navigation](https://github.com/w3c/wai-website-data/issues/17#issuecomment-841609497).

**Comment by remibetin** [comment]
Resolved by https://github.com/w3c/wai-intro-accessibility/pull/68
