### ISSUE TITLE
Indicating who is excluded when sites are badly developed[ED]

### ISSUE THREAD

**Issue by Sylduch-Conseil** [w3c/wai-intro-accessibility#7]
I think following sentence should indicate who is mainly concerned by poor designed web sites. 
"However, when websites, applications, technologies, or tools are badly designed, they can create barriers that exclude people from using the Web."
I think it is important to indicate that in most situations, people who are excluded are people with disabilities.
Proposed change: "However, when websites, applications, technologies, or tools are badly designed, they can create barriers that exclude people, in particular, those with disabilities, from using the Web."

**Comment by sharronrush** [comment]
However, as we have made the argument that accessibility improvements also make things easier for a wider group, in this case, people alone is most descriptive of who benefits.

**Comment by shawna-slh** [comment]
I agree that if there was just that one sentence without the surrounding context, that it would be important to specify people with disabilities.

Consider that:
* The previous sentence starts out: "Thus the impact of disability...
* Many people will automatically think of disability from the phrase "barriers that exclude"
* The rest of the page clearly talks about people with disabilities.
* This section was carefully crafted to reach readers who are not accessibility or disability friendly.

Given those considerations, are you OK with not adding people with disabilities to this one sentence?

If not, feel free to re-open this issue and we can discuss. Thanks!
