### ISSUE TITLE
[!!]Concerning other people who benefit from web accessibility

### ISSUE THREAD

**Issue by Sylduch-Conseil** [w3c/wai-intro-accessibility#8]
Actual text: 
"Web accessibility also benefits people without disabilities, for example:
• people using mobile phones, smart watches, digital TVs, etc.
• older people with changing abilities due to ageing
• people with "temporary disabilities" such as a broken arm
• people is an environment where they cannot listen to audio
• people using a slow Internet connection, or how have limited or expensive bandwidth"
I would change the order of people listed here, as I think that people using mobile phones are less excluded than others when a content is not accessible. If we want to make the text shorter, I would remove them from the list. 
The first sentence says that Web accessibility also benefits people withouth disabilities.
But older people or those with temporary disabilities have a sort of disability. 
Suggested change:
Web accessibility also benefits other people such as, for example:
• older people with changing abilities due to ageing
• people with "temporary disabilities" such as a broken arm"
• people in an environment where they cannot listen to audio
• people using a slow Internet connection, or how have limited or expensive bandwidth
???people using mobile phones, smart watches, digital TVs, etc.

**Comment by bakkenb** [comment]
+1

**Comment by sharronrush** [comment]
I had no problem with the mobile phone sentence since the variety of screen is implied.

**Comment by shawna-slh** [comment]
Thanks for the input!

The point of this sentence and list is to show that **while accessibility focuses on people with disabilities, it also benefits others**. Here it is in context: [What is Web Accessibility](https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#what)

I agree that "older people or those with temporary disabilities have a sort of disability" -- although they are not usually considered "people with a disability".

Many designers and developers are focused on mobile design these days. For that reason, it seems like it would be good to list that one first -- to show that this is directly beneficial to them, even if they aren't aware of the needs of people with disabilities.

Given these considerations:
* I prefer to leave as the first bullet "people using mobile phones, smart watches, digital TVs, etc."
* I mildly prefer to leave
> Web accessibility also benefits people _without_ disabilities, for example:...
* However, I could be talked into changing it to:
> Web accessibility also benefits other people, for example:...

What do y'all (EOWG and beyond) think?

**Comment by bakkenb** [comment]
I am comfortable with leaving it to editor's discretion. Thank you for the explanations.

**Comment by shawna-slh** [comment]
Based on feedback from [18 Jan teleconference](https://www.w3.org/2018/01/18-eo-minutes.html#item06), leaving:

> Web accessibility also benefits people without disabilities, for example:...

Issue about first bullet being addressed in https://github.com/w3c/wai-intro-accessibility/issues/12

If you want additional consideration, re-open issue.
