### ISSUE TITLE
Link destination not updated?

### ISSUE THREAD

**Issue by visanju** [w3c/wai-intro-accessibility#86]
I think the first link on line 112 is probably incorrect.
"Shared Web Experiences: Barriers Common to Mobile Device Users and People with Disabilities" is an archived resource and replaced by "https://www.w3.org/WAI/mobile/"

`-   If you want more examples of benefits for others, see the mobile resource [[Shared Web Experiences: Barriers Common to Mobile Device Users and People with Disabilities]](/standards-guidelines/shared-experiences/), multimedia [Used by People With and Without Disabilities](/media/av/users-orgs/#situations), and the archived [Web Accessibility Benefits People With and Without Disabilities](https://www.w3.org/WAI/business-case/archive/soc#groups).`

May be it should be:

-   If you want more examples of benefits for others, see the mobile resource [[Mobile Accessibility at W3C]](https://www.w3.org/WAI/mobile/), multimedia [Used by People With and Without Disabilities](/media/av/users-orgs/#situations), and the archived [Web Accessibility Benefits People With and Without Disabilities](https://www.w3.org/WAI/business-case/archive/soc#groups).

or 

-   If you want more examples of benefits for others, see the archived mobile resource [[Shared Web Experiences: Barriers Common to Mobile Device Users and People with Disabilities]](/standards-guidelines/shared-experiences/), multimedia [Used by People With and Without Disabilities](/media/av/users-orgs/#situations), and the archived [Web Accessibility Benefits People With and Without Disabilities](https://www.w3.org/WAI/business-case/archive/soc#groups).

**Comment by remibetin** [comment]
Thanks @visanju!

It is indeed voluntary to link to an archived resource. I have opened a PR, opting for your second proposal.
